#!/usr/bin/env bash
set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

ROLE="${1:-}"
case "$ROLE" in lava|flame|dell) export GEN="$ROLE" ;; esac
source "$SCRIPT_DIR/../vars.sh"

if [[ ! "$ROLE" =~ ^(sender|dut|receiver|lava|flame|dell)$ ]]; then
  echo "Usage: $0 [sender|dut|receiver|lava|flame|dell]"
  exit 1
fi

echo "=== FastACL Hardware Lab — Host Setup ($ROLE) ==="

echo ""
echo "[1/4] Configuring hugepages..."

current_hp=$(cat /sys/kernel/mm/hugepages/hugepages-1048576kB/nr_hugepages 2>/dev/null || echo 0)
echo "  Current 1GB hugepages: $current_hp"

if [ "$current_hp" -lt "$HUGEPAGES_NR" ]; then
  echo "  Allocating $HUGEPAGES_NR x 1GB hugepages..."
  echo "$HUGEPAGES_NR" > /sys/kernel/mm/hugepages/hugepages-1048576kB/nr_hugepages
  new_hp=$(cat /sys/kernel/mm/hugepages/hugepages-1048576kB/nr_hugepages)
  if [ "$new_hp" -lt "$HUGEPAGES_NR" ]; then
    echo "  WARNING: Only got $new_hp of $HUGEPAGES_NR hugepages."
    echo "  For reliable allocation, add to kernel cmdline:"
    echo "    hugepagesz=1G hugepages=$HUGEPAGES_NR"
  else
    echo "  Allocated $new_hp x 1GB hugepages."
  fi
else
  echo "  Already have $current_hp hugepages (>= $HUGEPAGES_NR). OK."
fi

HP2M_FILE="/sys/kernel/mm/hugepages/hugepages-2048kB/nr_hugepages"
HP2M_NEED=3072
current_2m=$(cat "$HP2M_FILE" 2>/dev/null || echo 0)
echo "  Current 2MB hugepages: $current_2m (need >= $HP2M_NEED for 2M buffer pool)"
if [ "$current_2m" -lt "$HP2M_NEED" ]; then
  echo "  Pre-allocating $HP2M_NEED x 2MB hugepages for VPP buffer pool..."
  echo "$HP2M_NEED" > "$HP2M_FILE"
  got=$(cat "$HP2M_FILE")
  echo "  Allocated: $got x 2MB hugepages"
fi

if ! mount | grep -q 'hugetlbfs.*pagesize=2M\|hugetlbfs.*on /dev/hugepages '; then
  echo "  Mounting 2MB hugetlbfs at /dev/hugepages..."
  mkdir -p /dev/hugepages
  mount -t hugetlbfs -o pagesize=2M nodev /dev/hugepages
fi

if ! mount | grep -q 'pagesize=1G\|pagesize=1024M'; then
  echo "  Mounting 1GB hugetlbfs at /dev/hugepages1G..."
  mkdir -p /dev/hugepages1G
  mount -t hugetlbfs -o pagesize=1G none /dev/hugepages1G
fi

if ! grep -q 'hugepages1G' /etc/fstab; then
  echo "  Adding /dev/hugepages1G to /etc/fstab..."
  echo "none /dev/hugepages1G hugetlbfs pagesize=1G 0 0" >> /etc/fstab
fi

if [ "$DPDK_DRIVER" = "mlx5" ]; then
  echo ""
  echo "[1b] Installing Mellanox MFT (mlxfwreset)..."
  if ! command -v mlxfwreset &>/dev/null; then
    UBUNTU_VER=$(lsb_release -sr 2>/dev/null || echo "22.04")
    MFT_URL="https://linux.mellanox.com/public/repo/mlnx_ofed/latest/ubuntu${UBUNTU_VER}/x86_64/"
    MFT_PKG=$(curl -fsSL "$MFT_URL" 2>/dev/null | grep -o 'mft_[^"]*_amd64\.deb' | head -1)
    if [ -n "$MFT_PKG" ]; then
      TMP=$(mktemp -d)
      curl -fsSL "${MFT_URL}${MFT_PKG}" -o "$TMP/mft.deb" && \
        dpkg -i "$TMP/mft.deb" && \
        echo "  Installed: $(mlxfwreset --version 2>&1 | head -1)" || \
        echo "  WARNING: MFT install failed — manual install may be needed"
      rm -rf "$TMP"
    else
      echo "  WARNING: Could not find MFT package for Ubuntu ${UBUNTU_VER} — skipping"
    fi
  else
    echo "  mlxfwreset already installed. OK."
  fi
fi

echo ""
echo "[2/4] DPDK NIC binding..."

if [ "$DPDK_DRIVER" = "mlx5" ]; then
  case "$ROLE" in
    dut)      PCIDEVS="$DUT_PCI_LEFT $DUT_PCI_RIGHT" ;;
    sender|lava|flame|dell) PCIDEVS="$SENDER_PCI $RECEIVER_PCI" ;;
    receiver) PCIDEVS="$RECEIVER_PCI" ;;
    *) PCIDEVS="" ;;
  esac

  for pci in $PCIDEVS; do
    if [ ! -e "/sys/bus/pci/devices/$pci/driver" ]; then
      echo "  Binding $pci to mlx5_core (was unbound)..."
      echo mlx5_core > "/sys/bus/pci/devices/$pci/driver_override"
      echo "$pci" > /sys/bus/pci/drivers_probe
    else
      drv=$(readlink "/sys/bus/pci/devices/$pci/driver" | xargs basename)
      echo "  $pci already bound to $drv. OK."
    fi
  done

  UDEV_RULE=/etc/udev/rules.d/70-fastacl-mlx5.rules
  if [ ! -f "$UDEV_RULE" ]; then
    echo "  Writing udev rule $UDEV_RULE for persistent binding..."
    cat > "$UDEV_RULE" <<'EOF'
# Bind Mellanox data-plane NICs to mlx5_core for DPDK bifurcated mode.
# Generated by labs/hw/setup-host.sh.
ACTION=="add", SUBSYSTEM=="pci", ATTR{vendor}=="0x15b3", ATTR{class}=="0x020000", \
  ATTR{driver_override}="mlx5_core", RUN+="/bin/sh -c 'echo %k > /sys/bus/pci/drivers_probe'"
EOF
    udevadm control --reload-rules 2>/dev/null || true
  fi
  echo "  Mellanox bifurcated mode configured."
else
  echo "  Binding NICs to $DPDK_DRIVER driver..."

  modprobe vfio-pci

  case "$ROLE" in
    sender)
      PCIDEVS="$SENDER_PCI"
      ;;
    dut)
      PCIDEVS="$DUT_PCI_LEFT $DUT_PCI_RIGHT"
      ;;
    receiver)
      PCIDEVS="$RECEIVER_PCI"
      ;;
    lava|flame|dell)
      PCIDEVS="$SENDER_PCI $RECEIVER_PCI"
      ;;
  esac

  for pci in $PCIDEVS; do
    echo "  Binding $pci to $DPDK_DRIVER..."
    if [ -e "/sys/bus/pci/devices/$pci/driver/unbind" ]; then
      echo "$pci" > "/sys/bus/pci/devices/$pci/driver/unbind"
    fi
    echo "$DPDK_DRIVER" > "/sys/bus/pci/devices/$pci/driver_override"
    echo "$pci" > /sys/bus/pci/drivers/$DPDK_DRIVER/bind
    echo "  $pci bound to $DPDK_DRIVER."
  done
fi

echo ""
echo "[3/4] Kernel parameters..."

if [ "$DPDK_DRIVER" = "vfio-pci" ]; then
  if ! dmesg | grep -qi "IOMMU enabled"; then
    echo "  WARNING: IOMMU may not be enabled."
    echo "  Add to kernel cmdline: intel_iommu=on iommu=pt"
    echo "  (or: amd_iommu=on iommu=pt)"
  else
    echo "  IOMMU is enabled. OK."
  fi
else
  echo "  Mellanox driver — no IOMMU changes needed."
fi

echo ""
echo "[4/4] Creating VPP runtime directory..."
mkdir -p /run/vpp
echo "  /run/vpp created."

echo ""
echo "=== Host setup complete for $ROLE ==="
echo ""
echo "Recommended kernel cmdline parameters (add to GRUB):"
echo "  hugepagesz=1G hugepages=$HUGEPAGES_NR"
if [ "$DPDK_DRIVER" = "vfio-pci" ]; then
  echo "  intel_iommu=on iommu=pt  (or amd_iommu=on iommu=pt)"
fi
if [ "$ROLE" = "dut" ] || [ "$ROLE" = "lava" ] || [ "$ROLE" = "flame" ]; then
  echo "  isolcpus=<cores>  (optional — isolate VPP worker cores from kernel scheduler)"
fi
