unix {
  cli-listen /run/vpp/cli.sock
  log /tmp/vpp-bf3.log
  full-coredump
  startup-config /tmp/fastacl-dpu-setup.vpp
  nodaemon
}
socksvr { socket-name /run/vpp/api.sock }
api-segment { prefix fastacl-bf3 }
memory {
  main-heap-size 4G
  main-heap-page-size 2M
}
dpdk {
  no-multi-seg
  no-tx-checksum-offload
  dev 0000:03:00.0 { name p0 num-rx-queues 12 num-tx-queues 12 num-rx-desc 4096 num-tx-desc 4096 rss { ipv4 ipv6 } }
  dev 0000:03:00.1 { name p1 num-rx-queues 12 num-tx-queues 12 num-rx-desc 4096 num-tx-desc 4096 rss { ipv4 ipv6 } }
}
cpu {
  main-core 0
  corelist-workers 1-12
}
buffers { buffers-per-numa 1048576 }
plugins {
  plugin fastacl_plugin.so { enable }
}
fastacl {
  license-file         /tmp/fastacl-lab-license.json
  tss-bihash-buckets   1048576
}
statseg { socket-name /run/vpp/stats.sock size 512M }
