unix {
  cli-listen /run/vpp/cli.sock
  log /tmp/vpp-dut.log
  full-coredump
  startup-config /src/labs/hw/dut/conf/setup.vpp
  nodaemon
}
socksvr {
  socket-name /run/vpp/api.sock
}
api-segment {
  prefix fastacl-dut
}
memory {
  main-heap-size 12G
  main-heap-page-size __DUT_HEAP_PAGE__
}
dpdk {
  no-multi-seg
  no-tx-checksum-offload
  dev __DUT_PCI_LEFT__  { name eth-left  num-rx-queues __DUT_NUM_QUEUES__ num-tx-queues __DUT_NUM_QUEUES__ num-rx-desc __DUT_RX_DESC__ num-tx-desc __DUT_TX_DESC__ rss { ipv4 ipv6 l3-src-only } devargs __DUT_DEVARGS__ }
  dev __DUT_PCI_RIGHT__ { name eth-right num-rx-queues __DUT_NUM_QUEUES__ num-tx-queues __DUT_NUM_QUEUES__ num-rx-desc __DUT_RX_DESC__ num-tx-desc 1024 rss { ipv4 ipv6 l3-src-only } devargs __DUT_DEVARGS__ }
}
cpu {
  main-core __DUT_MAIN_CORE__
  corelist-workers __DUT_WORKER_CORES__
}
buffers {
  buffers-per-numa __DUT_BUFFERS_PER_NUMA__
}
plugins {
  path __VPP_PLUGIN_PATH__
  plugin fastacl_plugin.so { enable }
}
fastacl {
  tss-bihash-buckets   1048576
  license-file         /tmp/fastacl-lab-license.json
}
statseg {
  socket-name /run/vpp/stats.sock
  size 12G
}
